swagger: "2.0"                                  # 基于Swagger 2.0版本实现
info:
  version: v1
  title: 单库上云
  description: 单库上云相关接口

basePath: /regions/{regionId}

paths:
  "/instances/{instanceId}/importFiles":    #单库上云文件
    get:
      description: 获取用户通过单库上云工具上传到该实例上的文件列表<br>- 仅支持SQL Server
      operationId: describeImportFiles
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  importFiles:
                    type: array
                    description: 导入文件的集合
                    items:
                      $ref: ../model/ImportFile.yaml#/definitions/ImportFile
  "/instances/{instanceId}/importFiles:getUploadKey":    #上传导入文件的需要的Key
    post:
      description: 获取单库上云工具上传文件的需要的Key。单库上云工具需要正确的key值方能连接到京东云<br>- 仅支持SQL Server
      operationId: getUploadKey
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  key:
                    type: string
                    description: 上传文件需要用到的Key
  "/instances/{instanceId}/importFiles/{fileName}:setShared":    #单库上云文件
    post:
      description: 设置或取消上传文件是否共享给同一账号下的其他实例。缺省情况下，文件仅在上传的实例上可见并可导入，其他实例不可见不可导入。如果需要该文件在其他实例上也可导入，可将此文件设置为共享<br>- 仅支持SQL Server
      operationId: setImportFileShared
      parameters:
        - name: shared
          in: body
          description: 文件是否共享
          schema:
            type: object
            required:
              - shared
            properties:
              shared:
                type: string
                description: 文件是否共享<br>true:共享<br>false:不共享
      responses:
        200:
          description: OK

#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: RDS 实例ID，唯一标识一个RDS实例
  fileName:
    name: fileName
    in: path
    required: true
    type: string
    description: 单库上云文件名

