swagger: "2.0"
definitions:
  Account:
    x-jdcloud-module: rds
    title: Account
    type: object
    properties:
      accountName:
        type: string
        description: 账号名，账号名的具体规则可参见帮助中心文档:[名称及密码限制](../../../documentation/Cloud-Database-and-Cache/RDS/Introduction/Restrictions/SQLServer-Restrictions.md)
      accountStatus:
        type: string
        description: 账号状态，参见[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)<br>- **MySQL：不支持，不返回该字段**<br>- **SQL Server：返回该字段**
      accountPrivileges:
        type: array
        items:
          $ref: "../model/AccountPrivilege.yaml#/definitions/AccountPrivilege"
          description: 账户权限
        description: 具有的权限