swagger: "2.0"
definitions:
  AccountPrivilege:
    x-jdcloud-module: rds
    title: AccountPrivilege
    type: object
    properties:
      dbName:
        type: string
        description: 数据库名称，具体规则可参见帮助中心文档:[名称及密码限制](../../../documentation/Cloud-Database-and-Cache/RDS/Introduction/Restrictions/SQLServer-Restrictions.md)
      privilege:
        type: string
        description: 账号对数据库所具有的权限，权限的具体定义可以参见[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)