swagger: "2.0"
definitions:
  DBAccessPrivilege:
    x-jdcloud-module: rds
    title: DBAccessPrivilege
    type: object
    properties:
      accountName:
        type: string
        description: 账号名称
      privilege:
        type: string
        description: 该账号对数据库具有的权限，权限的具体定义可以参见[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)