swagger: "2.0"
definitions:
  DBInstanceSpec:
    x-jdcloud-module: rds
    title: DBInstanceSpec
    type: object
    required:
      - engine
      - engineVersion
      - instanceClass
      - instanceStorageGB
      - azId
      - vpcId
      - subnetId
      - chargeSpec
    properties:
      instanceName:
        type: string
        description: 实例名，具体规则可参见帮助中心文档:[名称及密码限制](../../../documentation/Cloud-Database-and-Cache/RDS/Introduction/Restrictions/SQLServer-Restrictions.md)
      engine:
        type: string
        description: 实例引擎类型，参见[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)
      engineVersion:
        type: string
        description: 实例引擎版本，参见[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)
      instanceClass:
        type: string
        description: 实例规格代码，可以通过[describeInstanceClasses](../instance/describeInstanceClasses.md)接口获取
      instanceStorageGB:
        type: integer
        description: 磁盘大小，单位GB
      azId:
        type: array
        items:
          type: string
          description: 可用区ID
        description: 可用区ID， 第一个ID必须为主实例所在的可用区。如两个可用区一样，也需输入两个azId
      vpcId:
        type: string
        description: VPC的ID
      subnetId:
        type: string
        description: 子网ID
      chargeSpec:
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: 计费规格，包括计费类型，计费周期等