swagger: "2.0"
definitions:
  ImportFile:
    x-jdcloud-module: rds
    title: ImportFile
    type: object
    properties:
      name:
        type: string
        description: 文件名称
      sharedFileGid:
        type: string
        description: 如果该文件是共享文件，则有全局ID，如不是共享文件，则为空。该全局ID在文件删除时，需要用到
      sizeByte:
        type: integer
        description: 文件大小，单位Byte
      uploadTime:
        type: string
        description: 文件上传完成时间，格式为：YYYY-MM-DD HH:mm:ss
      isLocal:
        type: string
        description: 是否所属当前实例.<br> 1：当前实例；<br>0：不是当前实例，为共享文件