swagger: "2.0"
info:
  version: "v1"
  title: 安全组
  description: 安全组相关接口

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/networkSecurityGroups/":
     get:
       summary: "查询安全组列表"
       description: "查询安全组列表"
       operationId: describeNetworkSecurityGroups

       parameters:
         - name: pageNumber
           in: query
           type: integer
           default: 1
           minimum: 1
           description: 页码, 默认为1, 取值范围：[1,∞), 页码超过总页数时, 显示最后一页
         - name: pageSize
           in: query
           type: integer
           default: 20
           minimum: 10
           maximum: 100
           description: 分页大小，默认为20，取值范围：[10,100]
         - name: filters
           in: query
           type: array
           items:
             #$ref: "/jcloud-open-api/common/model/Filter.yaml#/definitions/filter"
             $ref: "../../common/model/Filter.yaml#/definitions/filter"
           description: |
                  networkSecurityGroupIds - 安全组ID列表，支持多个
                  networkSecurityGroupNames - 安全组名称列表，支持多个
                  vpcId	- 安全组所属vpc Id，支持单个

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "返回结果"
                 properties:
                   networkSecurityGroups:
                     description: "安全组资源信息列表"
                     type: array
                     items:
                       $ref: "../model/NetworkSecurityGroup.yaml#/definitions/networkSecurityGroup"
                   totalCount:
                     description: "总数量"
                     type: number
               requestId:
                 description: "请求ID"
                 type: string
         400:
            description: "invalid parameter"
         401:
            description: "Authentication failed"

     #create networkSecurityGroup
     post:
       summary: "创建安全组"
       description: "创建安全组"
       operationId: createNetworkSecurityGroup
       parameters:
         - name: networkSecurityGroupSpec
           in: body
           required: true
           description: "创建安全组请求参数"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/NetworkSecurityGroupSpec.yaml#/definitions/networkSecurityGroupSpec"

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "返回结果"
                 properties:
                   networkSecurityGroupId:
                     description: "安全组ID"
                     type: string
               requestId:
                 description: "请求ID"
                 type: string
         400:
            description: "invalid parameter"
         404:
            description: "Resource not found"
         500:
            description: "Internal server error"


  "/networkSecurityGroups/{networkSecurityGroupId}":
     #describe networkSecurityGroup
     get:
       summary: 查询安全组信息详情
       description: 查询安全组信息详情
       operationId: describeNetworkSecurityGroup

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "返回结果"
                 properties:
                   networkSecurityGroup:
                      description: "安全组资源信息"
                      $ref: "../model/NetworkSecurityGroup.yaml#/definitions/networkSecurityGroup"
               requestId:
                 description: "请求ID"
                 type: string
         400:
            description: "invalid parameter"
         401:
            description: "Authentication failed"

     #modify networkSecurityGroup
     patch:
       summary: 修改安全组属性
       description: 修改安全组属性
       operationId: modifyNetworkSecurityGroup

       parameters:
         - name: modifyNetworkSecurityGroupSpec
           in: body
           required: true
           description: "修改安全组"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/ModifyNetworkSecurityGroupSpec.yaml#/definitions/modifyNetworkSecurityGroupSpec"
       responses:
         200:
           description: OK
           schema:
             properties:
               requestId:
                 description: "请求ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

     #delete networkSecurityGroup
     delete:
         summary: 删除安全组
         description: 删除安全组
         operationId: deleteNetworkSecurityGroup

         responses:
           200:
             description: OK
             schema:
               properties:
                 requestId:
                   description: "请求ID"
                   type: string
           400:
             description: invalid parameter
           404:
             description: Resource not found
           500:
             description: Internal server error

  #add security group rules
  "/networkSecurityGroups/{networkSecurityGroupId}:addNetworkSecurityGroupRules":
    post:
      summary: "添加安全组规则"
      description: "添加安全组规则"
      operationId: addNetworkSecurityGroupRules
      parameters:
        - name: addNetworkSecurityGroupRulesSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/AddNetworkSecurityGroupRulesSpec.yaml#/definitions/addNetworkSecurityGroupRulesSpec"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "请求ID"
                 type: string
        400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
        404:
           description: Resource not found
        409:
           description: SecurityGroup rules not in the same vpc
        500:
           description: Internal server error

  #remove security group rules
  "/networkSecurityGroups/{networkSecurityGroupId}:removeNetworkSecurityGroupRules":
    post:
      summary: "移除安全组规则"
      description: "移除安全组规则"
      operationId: removeNetworkSecurityGroupRules
      parameters:
        - in: body
          name: ruleIds
          description: 安全组规则Id列表
          required: true
          schema:
            type: array
            items:
              type: string

      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "请求ID"
                 type: string
        400:
           description: "Request field x.y.z is missing."
        404:
           description: "Target 'xxx' not found; TargetGroup 'xxx' not found."
        500:
           description: "internal server error"
  
  #modify security group rules         
  "/networkSecurityGroups/{networkSecurityGroupId}:modifyNetworkSecurityGroupRules":
    post:
      summary: "修改安全组规则"
      description: "修改安全组规则"
      operationId: modifyNetworkSecurityGroupRules
      parameters:
        - name: modifySecurityGroupRuleSpecs
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/ModifyNetworkSecurityGroupRulesSpec.yaml#/definitions/modifySecurityGroupRuleSpec"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "请求ID"
                 type: string
        400:
           description: "invalid parameter"
        404:
           description: "SecurityGroup or SecurityGroupRule not found"
        500:
           description: Internal server error
  
  "/networkSecurityGroups/{networkSecurityGroupId}:associateSecurityGroup":
     post:
       description: "绑定安全组接口"
       operationId: associateSecurityGroup
       x-jdcloud-internal: true
       parameters:
        - name: networkInterfaceIds
          in: body
          required: true
          description: "安全组要绑定的弹性网卡ID列表，每个弹性网卡最多绑定5个安全组"
          schema:
            type: array
            items:
              type: string
       
       responses:
         200:
           description: Successful operation
           schema:
             type: object
             properties:
               requestId:
                 description: "请求ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

  "/networkSecurityGroups/{networkSecurityGroupId}:disassociateSecurityGroup":
     post:
       description: "解绑安全组接口"
       operationId: disassociateSecurityGroup
       x-jdcloud-internal: true
       parameters:
        - name: networkInterfaceId
          in: query
          required: true
          type: string
          description: "安全组要解绑的弹性网卡ID"

       responses:
         200:
           description: "Successful operation"
           schema:
             type: object
             properties:
               requestId:
                 description: "请求ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  networkSecurityGroupId:
    name: networkSecurityGroupId
    in: path
    required: true
    type: string
    description: NetworkSecurityGroup ID
