swagger: "2.0"
info:
  version: "v1"
  title: 网段
  description: 网段相关接口

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/segments/":
     #describe segments
    get:
      summary: "查询网段列表"
      description: "查询网段列表"
      operationId: describeSegments
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: "页码, 默认为1, 取值范围：[1,∞), 页码超过总页数时, 显示最后一页"
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: "分页大小，默认为20，取值范围：[10,100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
                 segmentIds - 网段ID列表，支持多个
                 segmentNames - 网段名称列表,支持多个
                 provider - IP服务商，取值为bgp或no_bgp，cn-north-1：bgp；cn-south-1：[bgp，no_bgp]；cn-east-1：[bgp，no_bgp]；cn-east-2：bgp，支持单个
    
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "返回结果"
                properties:
                  segments:
                    description: "网段资源信息列表"
                    type: array
                    items:
                      $ref: "../model/Segment.yaml#/definitions/segment"
                  totalCount:
                    description: "总数量"
                    type: number
              requestId:
                description: "请求ID"
                type: string

  "/segments/{segmentId}":
      #describe segment
      get:
        summary: "查询网段信息详情"
        description: "查询网段信息详情"
        operationId: describeSegment
        x-jdcloud-internal: true
        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "返回结果"
                  properties:
                    segment:
                      description: "网段资源信息"
                      $ref: "../model/Segment.yaml#/definitions/segment"
                requestId:
                  description: "请求ID"
                  type: string
          400:
            description: "invalid parameter"
          401:
            description: "Authentication failed"

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  segmentId:
    name: segmentId
    in: path
    required: true
    type: string
    description: 网段 ID
