swagger: "2.0"
info:
  version: "v1"
  title: 网站监控
  description: 云解析OpenAPI网站监控接口

basePath: /regions/{regionId}

paths:
  /domain/{domainId}/monitor:
  ###################### 查看主域名的监控项 ######################
    get:
      description: "查看主域名的监控项的配置以及状态"
      operationId: getMonitor
      parameters:
        - name: pageIndex
          in: query
          type: integer
          required: false
          description: 当前页数，起始值为1，默认为1
        - name: pageSize
          in: query
          type: integer
          required: false
          description: 分页查询时设置的每页行数
        - name: searchValue
          in: query
          type: string
          required: false
          description: 查询的值
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  currentCount:
                    type: integer
                    description: 当前页面网站监控项的个数
                  totalCount:
                    type: integer
                    description: 所有网站监控项的个数
                  totalPage:
                    type: integer
                    description: 所有网站监控项的页数
                  dataList:
                    description: 当前页面的网站监控项的列表
                    type: array
                    items:
                      $ref: "../model/Monitor.yaml#/definitions/monitor"
              requestId:
                type: string
                description: 此次请求的ID
        400:
          description: BAD_REQUEST
  /domain/{domainId}/monitorAdd:
  ###################### 添加域名的监控项，默认设置 ######################
    post:
      description: "添加子域名的监控项，默认把子域名的所有监控项都添加上监控"
      operationId: addMonitor
      parameters:
        - name: subDomainName
          in: query
          type: string
          required: true
          description: 子域名
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: 此次请求的ID
        400:
          description: BAD_REQUEST  
          
  /domain/{domainId}/getTargets:
  ###################### 查询子域名的可用监控对象 ######################
    get:
      description: "查询子域名的可用监控对象"
      operationId: getTargets
      parameters:
        - name: subDomainName
          in: query
          type: string
          required: true
          description: 子域名
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  data:
                    description: 返回的可用监控对象的数组
                    type: array
                    items:
                      type: string  
              requestId:
                type: string
                description: 此次请求的ID
        400:
          description: BAD_REQUEST  
  
  /domain/{domainId}/monitorAddTarget:
  ###################### 添加子域名的监控项 ######################
    post:
      description: "添加子域名的某些特定监控对象为监控项"
      operationId: addMonitorTarget
      parameters:
        - name: subDomainName
          in: query
          type: string
          required: true
          description: 子域名
        - name: targets
          description: 子域名可用监控对象的数组         
          in: query
          required: true 
          type: array
          items:
            type: string
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: 此次请求的ID
        400:
          description: BAD_REQUEST 
          
  /domain/{domainId}/monitorOperate:
  ###################### 监控项操作，包括：删除，暂停，启动, 手动恢复, 手动切换 ######################
    post:
      description: "监控项的操作集合，包括：删除，暂停，启动, 手动恢复, 手动切换"
      operationId: operateMonitor
      parameters:
        - name: action
          in: query
          type: string
          required: true
          description: 删除del, 暂停stop, 开启start, 手动恢复recover，手动切换switch
        - name: ids
          in: query
          type: array
          items:
            type: integer
          required: true
          description: 监控项ID
        - name: switchTarget
          in: query
          type: string
          required: false
          description: 监控项的主机值, 手动切换时必填
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: 此次请求的ID
        400:
          description: BAD_REQUEST
  /domain/{domainId}/monitorUpdate:
  ###################### 域名的监控项修改 ######################
    post:
      description: "域名的监控项修改"
      operationId: updateMonitor
      parameters:
        - name: updateMonitor
          description: 监控项设置信息
          in: body
          required: true
          schema:
            $ref: "../model/Monitor.yaml#/definitions/updateMonitor"       
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                type: string
                description: 此次请求的ID
        400:
          description: BAD_REQUEST
                 
  /domain/{domainId}/monitor/alarminfo:
  ###################### 主域名的监控项的报警信息 ######################
    get:
      description: "主域名的监控项的报警信息"
      operationId: getMonitorAlarmInfo
      parameters:
        - name: pageIndex
          in: query
          type: integer
          required: false
          description: 当前页数，起始值为1，默认为1
        - name: pageSize
          in: query
          type: integer
          required: false
          description: 分页查询时设置的每页行数
        - name: searchValue
          in: query
          type: string
          required: false
          description: 关键字
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  currentCount:
                    type: integer
                    description: 当前页面报警信息的个数
                  totalCount:
                    type: integer
                    description: 所有报警信息的个数
                  totalPage:
                    type: integer
                    description: 所有报警信息的页数
                  dataList:
                    type: array
                    description: 当前页面的报警信息的数组
                    items:
                      $ref: "../model/Monitor.yaml#/definitions/monitorAlarmInfo"
              requestId:
                type: string
                description: 此次请求的ID
        400:
          description: BAD_REQUEST
#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 实例所属的地域ID
  domainId:
    name: domainId
    in: path
    required: true
    type: string
    description: 域名ID