swagger: "2.0"
definitions:
  sort:
    x-jdcloud-module: common
    type: object
    properties:
      name:
        type: string
        description: 排序条件的名称
      direction:
        type: string
        description: 排序条件的方向
        enum:
          - asc
          - desc
