swagger: "2.0"
definitions:
  filter:
    x-jdcloud-module: common
    type: object
    required:
      - key
      - values
    properties:
      key:
        type: string
        description: 过滤条件的名称
      values:
        type: array
        description: 过滤条件的值
        items:
          type: string

