swagger: "2.0"
info:
  version: "v1"
  title: 售罄相关接口
  description: 查询售罄情况 

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/soldout":
   ###################### 查询售罄情况接口 ######################
    get:
      operationId: describeSoldout
      summary: "查询云硬盘售罄情况列表"
      description: "查询云硬盘售罄情况列表"
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                type: object
                description: "查询结果集"
                properties:
                  soldout:
                    type: array
                    description: "查询的售罄情况详情列表"
                    items:
                      $ref: "../model/Soldout.yaml#/definitions/soldout"
                  totalCount:
                    type: integer
                    description: "查询的可用区售罄情况数目"
              requestId:
                type: string
                description: "请求ID"
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域ID

