swagger: "2.0"
definitions:
  addSecurityGroupRules:
    x-jdcloud-module: vpc
    required:
      - protocol
      - direction
      - addressPrefix
    properties:
      protocol:
        type: number
        description: 规则限定协议。300:All; 6:TCP; 17:UDP; 1:ICMP
      direction:
        type: number
        description: 安全组规则方向。0：入规则; 1：出规则
      addressPrefix:
        type: string
        description: 匹配地址前缀
      fromPort:
        type: number
        description: 规则限定起始传输层端口, 取值范围:1-65535, 若protocol为传输层协议，默认值为1，若protocol不是传输层协议，恒为0。如果规则只限定一个端口号，fromPort和toPort填写同一个值
      toPort:
         type: number
         description: 规则限定终止传输层端口, 取值范围:1-65535, 若protocol为传输层协议，默认值为65535，若protocol不是传输层协议，恒为0。如果规则只限定一个端口号，fromPort和toPort填写同一个值
      description:
         type: string
         description: 描述,​ 允许输入UTF-8编码下的全部字符，不超过256字符

