swagger: "2.0"
definitions:
  assignSecondaryIpsSpec:
    x-jdcloud-module: vpc
    properties:
        force:
          type: boolean
          description: secondary ip被其他接口占用时，是否抢占。false：非抢占重分配，true：抢占重分配，默认抢占重分配。默认值：true
          default: true
        secondaryIps:
          type: array
          items:
            type: string
          description: 指定分配的secondaryIp地址
        secondaryIpCount:
          type: number
          description: 指定自动分配的secondaryIp个数
