swagger: "2.0"
definitions:
  disassociateRouteTableSpec:
    x-jdcloud-module: vpc
    required:
      - subnetId
    properties:
      subnetId:
        type: string
        description: 路由表要解绑的子网ID，解绑后子网绑定默认路由表



