swagger: "2.0"
definitions:
  disassociateElasticIpSpec:
    x-jdcloud-module: vpc
    properties:
      elasticIpId:
        type: string
        description: 指定解绑的弹性Ip Id
      elasticIpAddress:
        type: string
        description: 指定解绑的弹性Ip地址
