swagger: "2.0"
definitions:
  modifyNetworkAclRuleSpec:
    x-jdcloud-module: vpc
    required:
      - ruleId
    properties:
      ruleId:
        type: string
        description: networkAcl规则ID
      protocol:
        type: string
        description: 规则限定协议。取值范围：All,TCP,UDP,ICMP
      fromPort:
        type: integer
        description: 规则限定起始传输层端口, 取值范围:1-65535, 若protocol为传输层协议，默认值为1，若protocol不是传输层协议，设置无效，恒为0。如果规则只限定一个端口号，fromPort和toPort填写同一个值
      toPort:
        type: integer
        description: 规则限定终止传输层端口, 取值范围:1-65535, 若protocol为传输层协议，默认值为65535，若protocol不是传输层协议，设置无效，恒为0。如果规则只限定一个端口号，fromPort和toPort填写同一个值
      addressPrefix:
        type: string
        description: 匹配地址前缀
      ruleAction:
        type: string
        description: 访问控制策略：allow:允许，deny：拒绝
      priority:
        type: integer
        description: 规则匹配优先级，取值范围为[1,32768]，优先级数字越小优先级越高
      description:
        type: string
        description: "描述,允许输入UTF-8编码下的全部字符，不超过256字符"