swagger: "2.0"
definitions:
  modifyNetworkSecurityGroupSpec:
    x-jdcloud-module: vpc
    properties:
      networkSecurityGroupName:
        type: string
        description: 安全组的名字。名称取值范围：1-32个中文、英文大小写的字母、数字和下划线分隔符
      description:
        type: string
        description: 安全组的描述，取值范围：0-256个UTF-8编码下的全部字符
