swagger: "2.0"
definitions:
  modifyQuotaSpec:
    x-jdcloud-module: vpc
    required:
      - type
      - maxLimit
    properties:
      type:
        type: string
        description: 资源类型，取值范围：vpc、elastic_ip、subnet、security_group、vpcpeering、network_interface（配额只统计辅助网卡）
      parentResourceId:
        type: string
        description: type为vpc、elastic_ip、network_interface不设置, type为subnet、security_group、vpcpeering设置为vpcId
      maxLimit:
        type: integer
        description: 配额大小
