swagger: "2.0"
definitions:
  modifySubnetSpec:
    x-jdcloud-module: vpc
    properties:
      subnetName:
        type: string
        description: 子网名称,只允许输入中文、数字、大小写字母、英文下划线“_”及中划线“-”，不允许为空且不超过32字符。
      description:
        type: string
        description: 子网描述信息，允许输入UTF-8编码下的全部字符，不超过256字符。


