swagger: "2.0"
definitions:
  modifyVpcSpec:
    x-jdcloud-module: vpc
    properties:
      vpcName:
        type: string
        description: 私有网络名称,只允许输入中文、数字、大小写字母、英文下划线“_”及中划线“-”，不允许为空且不超过32字符。
      description:
        type: string
        description: vpc描述，允许输入UTF-8编码下的全部字符，不超过256字符。


