swagger: "2.0"
definitions:
  modifyRouteTableRules:
    x-jdcloud-module: vpc
    required:
      - ruleId
    properties:
      ruleId:
        type: string
        description: 路由表规则的ID
      priority:
        type: number
        description: 规则匹配优先级，取值范围[1,255]。当路由规则子网掩码不同时，路由最长匹配优先；当路由规则子网掩码相同时, 按照优先级匹配转发, 优先级数字越小优先级越高，路由规则子网掩码相同、优先级相同、下一跳不同时，形成等价路由，不同下一跳负载均担。
      nextHopType:
        type: string
        description: 下一跳类型, 取值范围:instance:云主机, internet:公网, vpc_peering:vpc对等连接, bgw:边界网关
      nextHopId:
        type: string
        description: 下一跳id
      addressPrefix:
        type: string
        description: 路由表规则前缀, internet类型路由跟其他类型的路由，addressPrefix不允许重复