swagger: "2.0"
definitions:
  modifyNetworkInterfaceSpec:
    x-jdcloud-module: vpc
    properties:
      networkInterfaceName:
        type: string
        description: "弹性网卡名称,只允许输入中文、数字、大小写字母、英文下划线“_”及中划线“-”，不允许为空且不超过32字符"
      description:
        type: string
        description: "描述,允许输入UTF-8编码下的全部字符，不超过256字符"
      securityGroups:
        type: array
        items:
          type: string
        description: "以覆盖原有安全组的方式更新的安全组。如果更新安全组ID列表，最多5个安全组"

