swagger: "2.0"
definitions:
  networkInterface:
    x-jdcloud-module: vpc
    properties:
      networkInterfaceName:
        type: string
        description: 弹性网卡名称
      networkInterfaceId:
        type: string
        description: 弹性网卡ID
      az:
        type: string
        description: 可用区名称
      role:
        type: string
        description: 网卡角色，取值范围：Primary（主网卡）、Secondary（辅助网卡）
      macAddress:
        type: string
        description: 以太网地址
      vpcId:
        type: string
        description: 虚拟网络ID
      subnetId:
        type: string
        description: 子网ID
      networkSecurityGroupIds:
        type: array
        items:
          type: string
        description: 安全组ID列表
      sanityCheck:
        type: integer
        description: 源和目标IP地址校验，取值为0或者1
      primaryIp:
        $ref: "./NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: 网卡主IP
      secondaryIps:
        type: array
        items:
          $ref: "./NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: 网卡附属IP列表
      instanceType:
        type: string
        description: 关联实例类型，取值范围：vm
      instanceId:
        type: string
        description: 关联实例ID
      instanceOwnerId:
        type: string
        description: 实例所属的账号
      deviceIndex:
        type: integer
        description: 网卡在实例上的设备索引号，取值范围：[0,8]，0：辅助网卡未绑定设备，1：主网卡，2-8：辅助网卡已绑定设备
      description:
        type: string
        description: 网卡描述信息
      createdTime:
        type: string
        description: 弹性网卡创建时间