swagger: "2.0"
definitions:
  routeTableSpec:
    x-jdcloud-module: vpc
    required:
      - vpcId
      - routeTableName
    properties:
      vpcId:
        type: string
        description: 路由表所属的私有网络ID
      routeTableName:
        type: string
        description: 路由表名称，只允许输入中文、数字、大小写字母、英文下划线“_”及中划线“-”，不允许为空且不超过32字符。
      description:
        type: string
        description: 描述,​ 允许输入UTF-8编码下的全部字符，不超过256字符
