swagger: "2.0"
definitions:
  routeTable:
    x-jdcloud-module: vpc

    properties:
      routeTableId:
        type: string
        description: 路由表ID
      routeTableName:
        type: string
        description: 路由表名称，只允许输入中文、数字、大小写字母、英文下划线“_”及中划线“-”，不允许为空且不超过32字符。
      routeTableType:
        type: string
        description: 路由表类型，default：默认路由表，custom：自定义路由表
      description:
        type: string
        description: 路由表描述信息，允许输入UTF-8编码下的全部字符，不超过256字符。
      vpcId:
        type: string
        description: 私有网络ID
      routeTableRules:
        type: array
        items:
         $ref: "./RouteTableRule.yaml#/definitions/routeTableRule"
        description: 路由表规则信息
      subnetIds:
        type: array
        items:
          type: string
        description: 路由表绑定的子网列表
      createdTime:
        type: string
        description: 路由表创建时间

