swagger: "2.0"
definitions:
  securityGroupRule:
    x-jdcloud-module: vpc
    properties:
      ruleId:
        type: string
        description: 安全组规则ID
      direction:
        type: number
        description: 安全组规则方向。0：入规则; 1：出规则
      protocol:
        type: number
        description: 规则限定协议。300:All; 6:TCP; 17:UDP; 1:ICMP
      addressPrefix:
        type: string
        description: 匹配地址前缀
      ipVersion:
        type: number
        description: 匹配地址协议版本。4：IPv4
      fromPort:
        type: number
        description: 规则限定起始传输层端口, 默认1 ，若protocal不是传输层协议，恒为0
      toPort:
         type: number
         description: 规则限定终止传输层端口, 默认1 ，若protocal不是传输层协议，恒为0
      createdTime:
         type: string
         description: 安全组规则创建时间
      description:
         type: string
         description: 描述,​ 允许输入UTF-8编码下的全部字符，不超过256字符

