swagger: "2.0"
definitions:
  subnetSpec:
    x-jdcloud-module: vpc
    required:
      - vpcId
      - subnetName
      - addressPrefix
    properties:
      vpcId:
        type: string
        description: 子网所属vpc的Id
      subnetName:
        type: string
        description: 子网名称,只允许输入中文、数字、大小写字母、英文下划线“_”及中划线“-”，不允许为空且不超过32字符。
      addressPrefix:
        type: string
        description: 子网网段，vpc内子网网段不能重叠，cidr的取值范围：10.0.0.0/8、172.16.0.0/12和192.168.0.0/16及它们包含的子网，且子网掩码长度为16-28之间，如果vpc含有cidr，则必须为vpc所在cidr的子网
      routeTableId:
        type: string
        description: 子网关联的路由表Id, 默认为vpc的默认路由表
      description:
        type: string
        description: 子网描述信息,允许输入UTF-8编码下的全部字符，不超过256字符。

