swagger: "2.0"
definitions:
  vpc:
    x-jdcloud-module: vpc
    properties:
      vpcId:
        type: string
        description: Vpc的Id
      addressPrefix:
        type: string
        description: 如果为空，则不限制网段，如果不为空，10.0.0.0/8、172.16.0.0/12和192.168.0.0/16及它们包含的子网，且子网掩码长度为16-28之间
      description:
        type: string
        description: VPC 描述，取值范围：1~120个字符
      vpcName:
        type: string
        description: 私有网络名称，取值范围：1-60个中文、英文大小写的字母、数字和下划线分隔符
      aclIds:
        type: array
        items:
          type: string
          descriptipn: 同一vpc下的acl id 列表
      routeTableIds:
        type: array
        items:
          type: string
          description: 同一vpc下的 路由表id列表
      subnets:
        type: array
        items:
          $ref: "./Subnet.yaml#/definitions/subnet"
        description: 私有网络包含的子网列表
      createdTime:
        type: string
        description: vpc创建时间


