swagger: "2.0"
definitions:
  dataPointX:
    x-jdcloud-module: monitor
    type: object
    title: DataPointX
    required:
      - metric 
      - timestamp 
      - value
    properties:
      metric:
        description: 监控指标名称，长度不超过255字节，只允许英文、数字、下划线_、点.,  [0-9][a-z] [A-Z] [. _ ]， 其它会返回err
        type: string
      tags:
        type: object
        description: 数据维度，数据类型为map类型，最多五个标签，尽量不传或少传。总长度不大于255字节，只允许英文、数字、下划线_、点., [0-9][a-z] [A-Z] [. _ ]，  其它会返回err
        additionalProperties:
          type: string
      timestamp:
        type: integer
        format: int64
        description: 秒级时间戳，早于当前时间30天的不能写入；建议的上报时间戳：上报时间间隔的整数倍，如上报间隔为5s，则建议上报的时间戳为 timestamp = current timestamp - (current timestamp % time interval) = 1487647187 - （1487647187 % 5） = 1487647187 -2 = 1487647185
      value:
        type: object
        description: 监控的值。number or string。最大值为long.MAX_VALUE=9223372036854775807=263-1。累计类型的指标，累计到最大值后需要翻转为0，重新开始计数。翻转后不影响速率的计算。
  putBody:
    x-jdcloud-module: monitor
    type: object
    title: putBody
    required:
      - appCode 
      - serviceCode 
      - region
      - resourceId 
      - dataPoints
    properties:
      appCode:
        description: 目前统一用jcloud
        type: string
      serviceCode:
        type: string
        description: 资源的类型，取值vm,ip,database,storage,disk,cdn,redis,balance,nat_gw,db_ro,vpn,ddos等,新接入的产品要求与opentapi命名的产品线名称一致
      region:
        type: string
        description: 地域信息，如 cn-north-1 等
      resourceId:
        type: string
        description: 资源的唯一表示，一般为uuid
      dataPoints:
        description: 监控数据点
        type: array
        items:
          $ref: "dataPointX"