swagger: "2.0"
info:
 version: "v1"
 title: 消费管理
 description: 用户中心消费管理API接口

basePath: /regions/{regionId}

schemes:
 - http

paths:
  "/billStatisticsInfo":
    ###################### 查询资源账单，消费记录中的费用信息 ######################
    get:
      description: "查询资源账单，消费记录中的费用信息"
      operationId: queryBillStatisticsInfo
      parameters:
        - name: appCode
          in: query
          type: string
          required: true
          description: appCode
        - name: serviceCode
          in: query
          type: string
          required: true
          description: serviceCode
        - name: payState
          in: query
          type: integer
          required: true
          description: 支付状态
        - name: timeType
          in: query
          type: integer
          required: true
          description: 时间类型
        - name: startTime
          in: query
          type: string
          required: true
          description: 开始时间
        - name: endTime
          in: query
          type: string
          required: true
          description: 结束时间
        - name: queryType
          in: query
          type: integer
          required: true
          description: 查询类型
        - name: payType
          in: query
          type: integer
          required: true
          description: 支付类型
        - name: billingType
          in: query
          type: integer
          required: true
          description: 计费类型
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  totalFee:
                    type: number
                    description: 总金额
                  cashPayFee:
                    type: number
                    description: 现金支付金额
                  cashCouponPayFee:
                    type: number
                    description: 优惠券支付金额
                  balancePayFee:
                    type: number
                    description: 余额支付金额
                  arrearFee:
                    type: number
                    description: 欠费金额
                  billFee:
                    type: number
                    description: 账单金额
                  discountFee:
                    type: number
                    description: 折扣金额
              requestId:
                type: string
        404:
          description: NOT_FOUND
  "/consumeOverView":
    ###################### 查询消费总览 ######################
    get:
      description: "查询消费总览"
      operationId: queryConsumptionOverView
      parameters:
        - name: timeType
          in: query
          type: integer
          required: true
        - name: startTime
          in: query
          type: string
          required: true
        - name: endTime
          in: query
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  pin:
                    type: string
                  startTime:
                    type: string
                  endTime:
                    type: string
                  actualFee:
                    type: number
                  cashPayFee:
                    type: number
                  balancePayFee:
                    type: number
                  cashCouponPayFee:
                    type: number
                  arrearFee:
                    type: number
                  consumptionProductVoList:
                    type: array
                    items:
                      $ref: "../model/ConsumptionProduct.yaml#/definitions/consumptionProduct"
                  consumptionList:
                    type: map
                    properties:
                      key:
                        type: string
                      values:
                        $ref: "../model/ConsumptionProduct.yaml#/definitions/consumptionProduct"
              requestId:
                type: string
        404:
          description: NOT_FOUND
  "/resourceBills":
    ###################### 查询资源账单列表 ###################### 
    post:
      description: "查询资源账单列表"
      operationId: queryResourceBills
      parameters:
        - name: queryType
          in: query
          type: integer
          required: false
          description: 查询类别   1：资源账单   2：消费记录
        - name: appCode
          in: query
          type: string
          required: false
          description: appCode
        - name: serviceCode
          in: query
          type: string
          required: false
          description: serviceCode
        - name: billingType
          type: integer
          in: query
          required: false
          description: billingType
        - name: payType
          type: integer
          in: query
          required: false
          description: payType
        - name: payState
          type: integer
          in: query
          required: false
          description: payState
        - name: timeType
          type: integer
          in: query
          required: false
          description: timeType
        - name: startTime
          type: string
          in: query
          required: false
          description: startTime
        - name: endTime
          type: string
          in: query
          required: false
          description: endTime
        - name: ignoreZero
          type: integer
          in: query
          required: false
          description: ignoreZero
        - name: resourceId
          type: string
          in: query
          required: false
          description: resourceId
        - name: site
          type: integer
          in: query
          required: false
          description: site
        - name: role
          type: integer
          in: query
          required: false
          description: role
        - name: region
          type: string
          in: query
          required: false
          description: region
        - name: pageIndex
          in: query
          type: integer
          required: false
          description: pageIndex
        - name: pageSize
          in: query
          type: integer
          required: false
          description: pageSize
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  pagination:
                    $ref: "../model/Pagination.yaml#/definitions/pagination"
                  result:
                    type: array
                    items:
                      $ref: "../model/ResourceBillQueryResultItem.yaml#/definitions/resourceBillQueryResultItem"
              requestId:
                type: string
        404:
          description: NOT_FOUND
  "/resourceBills/{resourceId}":
    ###################### 查询资源账单详情 ###################### 
    post:
      description: "查询资源账单详情"
      operationId: queryConsumeRecords
      parameters:
        - name: queryType
          type: integer
          in: query
        - name: appCode
          type: string
          in: query
        - name: serviceCode
          type: string
          in: query
        - name: billingType
          type: integer
          in: query
        - name: payType
          type: integer
          in: query
        - name: payState
          type: integer
          in: query
        - name: timeType
          type: integer
          in: query
        - name: startTime
          type: string
          in: query
        - name: endTime
          type: string
          in: query
        - name: ignoreZero
          type: integer
          in: query
        - name: site
          type: integer
          in: query
        - name: role
          type: integer
          in: query
        - name: region
          type: string
          in: query
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  pagination:
                    $ref: "../model/Pagination.yaml#/definitions/pagination"
                  result:
                    type: array
                    items:
                      $ref: "../model/ConsumeRecord.yaml#/definitions/consumeRecord"
              requestId:
                type: string
        404:
          description: NOT_FOUND
  "/resourceOrder/{resourceId}/resourceName":
    ###################### 查询资源名称 ###################### 
    get:
      description: "查询用于在账单展示的资源名称信息"
      operationId: getResourceName
      parameters:
        - name: region
          type: string
          in: query
        - name: serviceCode
          type: string
          in: query
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  resourceName:
                    type: string
              requestId:
                type: string
        404:
          description: NOT_FOUND
  "/consumeBills":
    ###################### 查询消费记录列表 ###################### 
    post:
      description: "查询消费记录列表"
      operationId: queryConsumeBills
      parameters:
        - name: queryType
          type: integer
          in: query
        - name: appCode
          type: string
          in: query
        - name: serviceCode
          type: string
          in: query
        - name: billingType
          type: integer
          in: query
        - name: payType
          type: integer
          in: query
        - name: payState
          type: integer
          in: query
        - name: timeType
          type: integer
          in: query
        - name: startTime
          type: string
          in: query
        - name: endTime
          type: string
          in: query
        - name: ignoreZero
          type: integer
          in: query
        - name: resourceId
          type: string
          in: query
        - name: site
          type: integer
          in: query
        - name: role
          type: integer
          in: query
        - name: region
          type: string
          in: query
        - name: pageIndex
          in: query
          type: integer
        - name: pageSize
          in: query
          type: integer
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  pagination:
                    $ref: "../model/Pagination.yaml#/definitions/pagination"
                  result:
                    type: array
                    items:
                      $ref: "../model/ConsumeBillQueryResultItem.yaml#/definitions/consumeBillQueryResultItem"
              requestId:
                type: string
        404:
          description: NOT_FOUND
  "/consumeBills/{billId}":
    ###################### 查询消费记录详情 ###################### 
    get:
      description: "查询消费记录详情"
      operationId: getBillDetail
      parameters:
        - name: systemType
          type: integer
          in: query
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  billId:
                    type: number
                  pin:
                    type: string
                  site:
                    type: integer
                  region:
                    type: string
                  appCode:
                    type: string
                  appCodeName:
                    type: string
                  serviceCode:
                    type: string
                  serviceCodeName:
                    type: string
                  resourceId:
                    type: string
                  billingType:
                    type: integer
                  billingTypeName:
                    type: string
                  formula:
                    type: string
                  formulaStr:
                    type: string
                  startTime:
                    type: string
                  endTime:
                    type: string
                  createTime:
                    type: string
                  billFee:
                    type: number
                  billFee2:
                    type: number
                  discountFee:
                    type: number
                  couponId:
                    type: string
                  couponFee:
                    type: number
                  actualFee:
                    type: number
                  cashCouponFee:
                    type: number
                  balancePayFee:
                    type: number
                  cashPayFee:
                    type: number
                  arrearFee:
                    type: number
                  paySate:
                    type: integer
                  systemType:
                    type: integer
                  resourceName:
                    type: string
              requestId:
                type: string
        404:
          description: NOT_FOUND
  "/accounting/adminQueryBillStatisticsInfo":
    ################查询消费统计信息 运营后台#################
      post:
        description: "查询消费统计信息"
        operationId: adminQueryBillStatisticsInfo
        parameters:
          - name: billQueryCondition
            in: body
            required: true
            x-jdcloud-tiered: false
            description: ""
            schema:
              $ref: "../model/BillQueryCondition.yaml#/definitions/billQueryCondition"
        responses:
          200:
            description: OK
            schema:
              type: object
              properties:
                result:
                  $ref: "../model/BillStatisticsInfoVo.yaml#/definitions/billStatisticsInfoVo"
                requestId:
                  type: string
          404:
            description: NOT_FOUND
  "/isArrear":
###################### 查询用户是否欠费######################
    get:
      description: "查询用户是否欠费"
      operationId: isArrear
      parameters:
        - name: pin
          type: string
          in: query
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  result:
                    type: boolean
                    description: "结果"
              requestId:
                type: string
        404:
          description: NOT_FOUND
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
  billId:
    name: billId
    type: number
    required: true
    in: path
  resourceId:
    name: resourceId
    type: string
    required: true
    in: path
