swagger: "2.0"
definitions:
  secret:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: 机密数据
    properties:
      name:
        type: string
        description: 机密数据名称
      type:
        type: string
        description: 私密数据的类型，目前仅支持如下类型：docker-registry：用来和docker registry认证的类型
      createdAt:
        type: string
        description: 创建时间
      data:
        $ref: "./DockerRegistryData.yaml#/definitions/dockerRegistryData"
        description: 机密的数据