swagger: "2.0"
definitions:
  securityGroupSimple:
    x-jdcloud-module: nc
    x-jdcloud-internal: false
    type: object
    description: 描述网卡安全组的基本信息
    properties:
      groupId:
        type: string
        description: 安全组ID
      groupName:
        type: string
        description: 安全组名称