swagger: "2.0"
info:
  version: "v1"
  title: 用户管理接口
  description: 用户管理接口

paths:
  "/passwordPolicy":
    ###################### 更新密码策略 ######################
    put:
      description: "更新密码策略"
      operationId: updatePasswordPolicy
      x-jdcloud-internal: true
      parameters:
        - name: updatePasswordPolicyInfo
          in: body
          description: 密码策略信息
          required: true
          schema:
            $ref: "../model/PasswordPolicy.yaml#/definitions/passwordPolicy"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string
    ###################### 查询密码策略信息 ######################
    get:
      description: "查询密码策略信息"
      operationId: describePasswordPolicy
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  passwordPolicy:
                    $ref: "../model/PasswordPolicy.yaml#/definitions/passwordPolicy"
              requestId:
                type: string

    ###################### 删除密码策略 ######################
    delete:
      description: "删除密码策略"
      operationId: deletePasswordPolicy
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string
