swagger: "2.0"
definitions:
  passwordPolicy:
    x-jdcloud-module: iam
    required:
      - length
      - rule
      - age
      - expirationOperation
      - reusePrevention
      - retryTimes
      - validLoginDuration
    properties:
      length:
        type: integer
        description: 密码长度，6-20之间
      age:
        type: integer
        description: 密码有效期，0-1095之间
      expirationOperation:
        type: integer
        description: 过期重置类型：0-主账号重置，1-子账号重置
      reusePrevention:
        type: integer
        description: 历史密码检查次数,0-10之间
      retryTimes:
        type: integer
        description: 密码重试次数,1-16之间
      validLoginDuration:
        type: integer
        descritpion: 登录有效期，15-720之间
      rule:
        $ref: "./PasswordPolicyRule.yaml#/definitions/passwordPolicyRule"
        description: 密码字符类型，至少包含一种