swagger: "2.0"
definitions:
  passwordPolicyRule:
    x-jdcloud-module: iam
    required:
      - requireUppercaseCharacters
      - requireLowercaseCharacters
      - requireNumbers
      - requireSpecialCharacters
    properties:
      requireUppercaseCharacters:
        type: boolean
        description: 是否包含大写字母
      requireLowercaseCharacters:
        type: boolean
        description: 是否包含小写字母
      requireNumbers:
        type: boolean
        description: 是否包含数字
      requireSpecialCharacters:
        type: boolean
        description: 是否包含特殊字符