swagger: "2.0"
definitions:
  tagFilter:
    x-jdcloud-module: disk
    type: object
    required:
      - key
      - values
    properties:
      key:
        type: string
        description: Tag键
      values:
        type: array
        items:
          type: string
        description: Tag值
