swagger: "2.0"
info:
  version: "v1"
  title: 镜像仓库认证信息
  description: 关于镜像仓库认证信息的相关接口

basePath: /regions/{regionId}

paths:
  "/secrets":
    ###################### 创建 secret ######################
    post:
      description: |
        创建一个 secret，用于存放镜像仓库机密相关信息。
      operationId: createSecret
      parameters:
        - name: name
          in: query
          type: string
          required: true
          description: |
            机密数据名称，不能重复
        - name: secretType
          in: query
          type: string
          required: true
          description: |
            机密数据的类型，目前仅支持：docker-registry 类型，用来和docker registry认证的类型。
        - name: data
          in: body
          schema:
            $ref: "../model/DockerRegistryData.yaml#/definitions/dockerRegistryData"
          description: |
            机密的数据。<br>
            key 的有效字符包括字母、数字、-、_和.； <br>
            value 是 Base64 编码的字符串，不能包含换行符（在 linux 下使用 base64 -w 0选项），每个value长度上限为4KB，整个data的长度不能超过256KB; <br>
            必须包含server、username、password 字段，email 字段是可选的。<br>
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  secretName:
                    type: string
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### 查询secret列表 ######################
    get:
      description: |
        查询 secret 列表。<br> 
        此接口支持分页查询，默认每页20条。
      operationId: describeSecrets
      parameters:
        - name: pageNumber
          in: query
          type: integer
          description: "页码；默认为1"
        - name: pageSize
          in: query
          type: integer
          description: "分页大小；默认为20；取值范围[10, 100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            name - secret名称，支持模糊搜索
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                 properties:
                  secrets:
                    type: array
                    items:
                      $ref: "../model/Secret.yaml#/definitions/secret"
                  totalCount:
                    type: number
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/secrets/{name}":
    ###################### 查询 secret 详情 ######################
    get:
      description: |
        查询单个 secret 详情
      operationId: describeSecret
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  secret:
                    $ref: "../model/Secret.yaml#/definitions/secret"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"
    ###################### 删除 secret ######################
    delete:
      description: | 
        删除单个 secret
      operationId: deleteSecret
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  name:
    name: name
    in: path
    required: true
    type: string
    description: Secret Name
