swagger: "2.0"
definitions:
  auditLog:
    x-jdcloud-module: jmr
    title: auditLog
    type: object
    properties:
      id:
        type: number
      eventId:
        type: string
        description: 事件ID
      eventType:
        type: string
        description: 事件类型
      description:
        type: string
        description: 描述
      objectType:
        type: string
      objectId:
        type: number
      user:
        type: string
      eventTime:
        type: string
        format: data-time
      createTime:
        type: string
        format: data-time
      modifyTime:
        type: string
        format: date-time