swagger: "2.0"
definitions:
  hardWareStackData:
    x-jdcloud-module: jmr
    title: hardWareStackData
    type: object
    properties:
       disk:
         type: array
         items:
           $ref: "../model/Disk.yaml#/definitions/disk"
       scale:
         type: array
         items:
           $ref: "../model/Scale.yaml#/definitions/scale"