swagger: "2.0"
definitions:
  softStack:
    x-jdcloud-module: jmr
    title: softStack
    type: object
    properties:
      version:
        type: string
        description: JMR当前版本
      software:
        type: string
        description: |
           "所用软件名称及版本，如"
           "HADOOP-2.6.0|HIVE-1.2.1|SPARK-2.0.0|ALLUXIO-1.0.1|ZOOKEEPER-3.4.5|ZEPPELIN-0.6.1"


