swagger: "2.0"
definitions:
  instanceStatus:
    x-jdcloud-module: vm
    properties:
      instanceId:
        type: string
        description: 云主机ID
      status:
        type: string
        description: <a href="http://docs.jdcloud.com/virtual-machines/api/vm_status">参考云主机状态</a>